#-------------------------------
# Test description for config file.
#
# Author: Neiro
# Revision: 0.0.1 (20170522_1628)
#-------------------------------
#
# Core config
#
# Path to home (install dir), where application save his data
save_point: "/Users/neiro/Projects/IntelliJIdea/work/gmZbxLogrt/save_point.dat"
#
# Handler config
#
handler:
  file_name: "/var/log/system.log"
  regex: "^.*(com.apple).*(service only).*(Pushing respawn).*$"
  case_sensitivity: false